version: '3.9'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - airbnb-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: api-airbnb
    depends_on:
      - database
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge

volumes:
  postgres_data:

# => Run multiple containers at the same time
# Run: docker-compose up -d
# Stop: docker-compose down