version: '3.8'

services:
  app:
    build: .
    container_name: airbnb-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - airbnb-network
    restart: always

  db:
    image: postgres:14-alpine
    container_name: airbnb-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=airbnb
      - POSTGRES_USER=${DBMS_USERNAME}
      - POSTGRES_PASSWORD=${DBMS_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airbnb-network
    restart: always

  redis:
    image: redis:alpine
    container_name: airbnb-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - airbnb-network
    restart: always

networks:
  airbnb-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:

# => Run multiple containers at the same time
# Run: docker-compose up -d
# Stop: docker-compose down