spring:
  application:
    name: Airbnb backend
## Database
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ## File
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  ## Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: gqhao.dhti15a23hn@sv.uneti.edu.vn
    password: bhqqmgzwzayojyoz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

## End point api
api:
  prefix: "/api/v1"

## JWT
jwt:
  signerKey: "vZ0fUpFQ4ctcn0YkHjdpfBqlgSjW0V38vW/peMlzIBjyxO4sQRF2iqh829Lre/jq"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second

## Cloudinary
cloudinary:
  cloud_name: "dkxwnkii4"
  api_key: "122237874773556"
  api_secret: "GHD93O9ICu6_e3AP3Mp1IvEP_Lk"
