spring:
  application:
    name: Airbnb backend

  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  prefix: "/api/v1"

jwt:
  signerKey: "vZ0fUpFQ4ctcn0YkHjdpfBqlgSjW0V38vW/peMlzIBjyxO4sQRF2iqh829Lre/jq"
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second

url:
  api-province: "https://provinces.open-api.vn/api/p"
  api-district: "https://provinces.open-api.vn/api/d"
  api-ward: "https://provinces.open-api.vn/api/w/"