spring:
  application:
    name: Airbnb backend
  ## Database
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ## File
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  ## Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

## End point api
api:
  prefix: "/api/v1"

## JWT
jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 3600 #in second
  refreshable-duration: 36000 #in second

## Cloudinary
cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}
